import GlobalGradient from '@/components/app-layout/global-gradient'
import './globals.css'

import AppProviders from '@/components/app-layout/app-provider'

export const metadata = {
  title: 'Dparkr',
  description: 'Generated by create-solana-dapp',
  icons: {
    icon: '/favicon.ico',
  },
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className='h-screen w-full'>
        <GlobalGradient/>
        <AppProviders>
          {children}
        </AppProviders> 
      </body>
    </html>
  )
}
